version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-testtask_db}
      MYSQL_USER: ${DB_USER:-testuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-testpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./testtask
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./testtask:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=True
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data: